[
  { "word": "wahid", "translation": "one" },
  { "word": "ithnan", "translation": "two" },
  { "word": "thalatha", "translation": "three" },
  { "word": "arba'a", "translation": "four" },
  { "word": "khamsa", "translation": "five" },
  { "word": "sitta", "translation": "six" },
  { "word": "saba'a", "translation": "seven" },
  { "word": "thamanya", "translation": "eight" },
  { "word": "tis'a", "translation": "nine" },
  { "word": "ashara", "translation": "ten" },
  { "word": "ahad 'ashar", "translation": "eleven" },
  { "word": "ithna 'ashar", "translation": "twelve" },
  { "word": "thalatha 'ashar", "translation": "thirteen" },
  { "word": "arba'a 'ashar", "translation": "fourteen" },
  { "word": "khamsa 'ashar", "translation": "fifteen" },
  { "word": "sitta 'ashar", "translation": "sixteen" },
  { "word": "saba'a 'ashar", "translation": "seventeen" },
  { "word": "thamanya 'ashar", "translation": "eighteen" },
  { "word": "tis'a 'ashar", "translation": "nineteen" },
  { "word": " 'ishrun", "translation": "twenty" },
  { "word": "thalathun", "translation": "thirty" },
  { "word": "arba'un", "translation": "forty" },
  { "word": "khamsun", "translation": "fifty" },
  { "word": "sittun", "translation": "sixty" },
  { "word": "sab'un", "translation": "seventy" },
  { "word": "thamanun", "translation": "eighty" },
  { "word": "tis'un", "translation": "ninety" },
  { "word": "mi'a", "translation": "hundred" },
  { "word": "mi'atain", "translation": "two hundred" },
  { "word": "thalathmi'a", "translation": "three hundred" },
  { "word": "alf", "translation": "thousand" },
  { "word": "ahmar", "translation": "red" },
  { "word": "azraq", "translation": "blue" },
  { "word": "akhDar", "translation": "green" },
  { "word": "asfar", "translation": "yellow" },
  { "word": "abiyad", "translation": "white" },
  { "word": "aswad", "translation": "black" },
  { "word": "bunni", "translation": "brown" },
  { "word": "zahri", "translation": "orange" },
  { "word": "bordo", "translation": "burgundy" },
  { "word": "fozii", "translation": "pink" },
  { "word": "shamal", "translation": "north" },
  { "word": "janub", "translation": "south" },
  { "word": "sharq", "translation": "east" },
  { "word": "gharb", "translation": "west" },
  { "word": "shamali", "translation": "northern" },
  { "word": "janubi", "translation": "southern" },
  { "word": "sharqi", "translation": "eastern" },
  { "word": "gharbi", "translation": "western" },
  { "word": "akun", "translation": "to be" },
  { "word": "yadhhab", "translation": "to go" },
  { "word": "yakul", "translation": "to eat" },
  { "word": "yashrab", "translation": "to drink" },
  { "word": "yu'ti", "translation": "to give" },
  { "word": "yara", "translation": "to see" },
  { "word": "yaf'al", "translation": "to do" },
  { "word": "ya'ti", "translation": "to come" },
  { "word": "ya'rif", "translation": "to know" }
]


// ===================================================================================================================================


[
  { "word": "un", "translation": "one" },
  { "word": "deux", "translation": "two" },
  { "word": "trois", "translation": "three" },
  { "word": "quatre", "translation": "four" },
  { "word": "cinq", "translation": "five" },
  { "word": "six", "translation": "six" },
  { "word": "sept", "translation": "seven" },
  { "word": "huit", "translation": "eight" },
  { "word": "neuf", "translation": "nine" },
  { "word": "dix", "translation": "ten" },
  { "word": "rouge", "translation": "red" },
  { "word": "bleu", "translation": "blue" },
  { "word": "vert", "translation": "green" },
  { "word": "jaune", "translation": "yellow" },
  { "word": "orange", "translation": "orange" },
  { "word": "violet", "translation": "purple" },
  { "word": "noir", "translation": "black" },
  { "word": "blanc", "translation": "white" },
  { "word": "gris", "translation": "gray" },
  { "word": "rose", "translation": "pink" },
  { "word": "nord", "translation": "north" },
  { "word": "sud", "translation": "south" },
  { "word": "est", "translation": "east" },
  { "word": "ouest", "translation": "west" },
  { "word": "famille", "translation": "family" },
  { "word": "père", "translation": "father" },
  { "word": "mère", "translation": "mother" },
  { "word": "frère", "translation": "brother" },
  { "word": "sœur", "translation": "sister" },
  { "word": "grand-père", "translation": "grandfather" },
  { "word": "grand-mère", "translation": "grandmother" },
  { "word": "oncle", "translation": "uncle" },
  { "word": "tante", "translation": "aunt" },
  { "word": "cousin", "translation": "cousin" },
  { "word": "cousine", "translation": "cousin" },
  { "word": "chemise", "translation": "shirt" },
  { "word": "pantalon", "translation": "pants" },
  { "word": "robe", "translation": "dress" },
  { "word": "jupe", "translation": "skirt" },
  { "word": "chaussures", "translation": "shoes" },
  { "word": "chapeau", "translation": "hat" },
  { "word": "manteau", "translation": "coat" },
  { "word": "écharpe", "translation": "scarf" },
  { "word": "gants", "translation": "gloves" }
]



[
  { "word": "un", "translation": "one" },
  { "word": "deux", "translation": "two" },
  { "word": "trois", "translation": "three" },
  { "word": "quatre", "translation": "four" },
  { "word": "cinq", "translation": "five" },
  { "word": "six", "translation": "six" },
  { "word": "sept", "translation": "seven" },
  { "word": "huit", "translation": "eight" },
  { "word": "neuf", "translation": "nine" },
  { "word": "dix", "translation": "ten" }
]


[
  { "word": "Yī", "translation": "One" },
  { "word": "Èr", "translation": "Two" },
  { "word": "Sān", "translation": "Three" },
  { "word": "Sì", "translation": "Four" },
  { "word": "Wǔ", "translation": "Five" },
  { "word": "Liù", "translation": "Six" },
  { "word": "Qī", "translation": "Seven" },
  { "word": "Bā", "translation": "Eight" },
  { "word": "Jiǔ", "translation": "Nine" },
  { "word": "Shí", "translation": "Ten" }
]
